checks:
  php: true

filter:
  excluded_paths:
  - build/*
  - vendor/*

build:
  project_setup:
    before:
    - composer install

  tests:
    override:
    -
      command: 'composer test:php:cover'
      coverage:
        file: 'var/logs/coverage.xml'
        format: 'clover'
